config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :subscriptions
  resources :comments
  root to: "events#index"
  devise_for :users

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  validates :name, presence: true, length: {maximum: 35}

  after_commit :link_subscriptions, on: :create

  mount_uploader :avatar, AvatarUploader
  private

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: self.email)
      .update_all(user_id: self.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t("controllers.users.updated")
    else
      render :edit
    end
  end

  private
    def set_current_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:name, :email, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: user, html: { multipart: true }, data: {turbo: false } do |form| %>
  <%= render partial: "partials/form_errors", locals: {model: user} %>
  
  <div class="form-floating mb-3">
    <%= form.text_field :name, autofocus: true, autocomplete: "name",
                     placeholder: t('views.devise.name'), id: "floatingInput", class: "form-control" %>
    <%= form.label :name, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.email_field :email, autofocus: true, autocomplete: "email",
                      placeholder: t('views.devise.email'), id: "floatingInput", class: "form-control" %>
    <%= form.label :email, for: "floatingInput" %>
  </div>

  <div class="form-control mb-3">
    <%= form.label :avatar, class: "form-label", for: "imageFile" %>
    <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
    <%= form.file_field :avatar, type: "file", class: "form-control", id: "imageFile" %>
  </div>

  <div class="actions mb-3">
    <%= form.submit t('views.users.save'), class: 'btn btn-info' %>
  </div>

  <div class="actions mb-3">
    <%= link_to t('views.users.back'), :back %>
  </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon') %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<div class="row justify-content-center">
  <h3 class='text-center mb-5'><%= t('views.users.edit_title') %></h3>
  <div class="col-md-6">

    <%= render 'form', user: @user %>
    <%= link_to t('views.users.change_password'), edit_user_registration_path, class: 'btn btn-warning mb-3' %>

  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1 class="mb-3"><%= @user.name %></h1>

  <%= image_tag user_avatar(@user) %>

  <% if @user == current_user %>
    <p class="buffer-top">
    <%= link_to t('views.users.edit_profile'), edit_user_path(@user),
      class: "btn btn-info" %> 
    </p>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <% if @user.events.any? %>
        <h3 class="mt-5 mb-4"><%= t('views.users.organization') %></h3>
        <div class="row">
          <%= render partial: "events/event", collection: @user.events %>
        </div>
      <% else %>
        <p class="buffer-top"><%= t('views.users.user_nothing_organized') %></p>
      <% end %>
    </div>
  </div>
</div>