config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :subscriptions
  resources :comments
  root to: "events#index"
  devise_for :users

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: [:show]
  before_action :set_current_user_event, only: %i[edit update destroy]

  def index
    @events = Event.all
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: I18n.t("controllers.events.created")
    else

      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t("controllers.events.updated")
    else
      render :edit
    end
  end

  def destroy
    @event.destroy

    redirect_to events_url, notice: I18n.t("controllers.events.destroyed")
  end

  private
  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4 mb-3">
  <div class="thumbnail">
    <%= content_tag 'div', '', class: 'event-background',
      style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>
      <div class="thumbnail-inner event-info-inner">
        <div class="caption">
          <div class="event-description">
            <h3><%= link_to event.title, event_path(event) %></h3>
            <h3><small><%= l event.datetime, format: :long %></small></h3>
            <div class="buffer-both"><%= event.address %></div>
          </div>
          <div>
            <% event.visitors.each do |user| %>
              <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for @event, data: {turbo: false} do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-floating mb-3">
    <%= f.text_field :title, autofocus: true, autocomplete: "title",               placeholder: t('activerecord.attributes.event.title'),
                     id: "floatingInput", class: "form-control" %>
    <%= f.label :title, for: "floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= f.text_field :address, autofocus: true, autocomplete: "address",
                     placeholder: t('activerecord.attributes.event.address'), id: "floatingInput", class: "form-control" %>
    <%= f.label :address, for: "floatingInput" %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-floating mb-3">
    <%= f.text_area :description, autofocus: true, autocomplete: "              description",
                    placeholder: t('views.events.description'), id: "floatingTextarea2", class: "form-control" %>
    <%= f.label :description, for: "floatingTextarea2" %>
  </div>

  <div class="actions mb-3">
    <%= f.submit t('views.events.save'), class: 'btn btn-info' %>
  </div>

  <div class="actions mb-3">
     <%= link_to t('views.events.return'), :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h3 class='text-center mb-3'><%= t('views.events.edit_event') %></h3>
<div class="row justify-content-center">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<h1><%= t('views.events.events') %></h1>

<div class="buffer-both">
  <%= link_to t('views.events.create'), new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1><%= t('views.events.new_event') %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render "form" %>  
  </div>
</div>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
        style: "background-image: url(#{event_photo(@event)})" %>
        <div class="event-info-inner">
          <div class="col-md-6">
            <div class="event-description">
              <h1><%= @event.title %></h1>
              <h3><%= l @event.datetime, format: :long %></h3>
              <h3><small><%= link_to @event.address,
                  "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
              <p><%= @event.description %></p>
            </div>
            
            <% if current_user_can_edit?(@event) %>
              <div class="buffer-top">
                <%= link_to t('views.events.edit'), edit_event_path(@event),
                  class: 'btn btn-primary' %>
                <%= button_to t('views.events.delete'), event_path(@event), method: :delete, form: { data: { turbo_confirm: t('app.are_you_sure') } },class: 'btn btn-danger mt-2' %>
              </div>
            <% end %>
          </div>
        </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="event-photos">
        <div class="event-photo-gallery">
          <%= render partial: 'photos/photo', collection: @event.
            photos.except(@new_photo) %>
        </div>

        <div class="event-photo-form">
          <%= render partial: 'photos/form', locals: 
            {photo: @new_photo || @event.photos.build} %>
        </div>
      </div>

      <div class="event-comments buffer-top">
        <div class="buffer-both">
          <%= render partial: 'comments/form',
            locals: {comment: @new_comment || @event.comments.build} %>
        </div>

        <div class="buffer-both">
          <%= render partial: "comments/comment", collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4 mt-4">
      <div class="event-owner">
        <h4><%= t("views.events.call") %></h4>
          <p><%= render partial: "users/user", object: @event.user %></p>
      </div>
      <div class="event-subscriptions">
        <h4><%= t("views.events.will_go") %></h4>
      </div>
      <p>
        <%= render partial: "subscriptions/subscription", 
        collection: @event.subscriptions.except(@new_subscription) %> 
      </p>
      <% unless @event.user == current_user || @event.subscribers.include?(current_user) %>
        <div class="event-subscription-form">
          <h4><%= t("views.events.i_will_go") %></h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
              subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>